spring:
  application:
    name: fileServer-01 #服务名

server:
  port: 8762 #服务提供者端口
 
eureka:
  instance:
      instance-id: spring-cloud-front1    #id一定要与 application-two.yml 中id不同，不然2个实例会被覆盖
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/