spring:
  application:
    name: zipkin-miya #服务名
#服务链路追踪组件zipkin
  zipkin:
    base-url: http://localhost:9411

server:
  port: 9101  #服务提供者端口

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/     


