userName: Alex
bookTitle: Spring Boot入门教程

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8500 #服务器端口
  tomcat:
    uri-encoding: UTF-8  

#log配置
logging:
    path: C:/E/Spring-boot/demo/user/local/log
    level: 
      com: 
        favorites: DEBUG
        baomidou.mybatisplus.samples.quickstart: debug
      org: 
        springframework.web: INFO
        hibernate: ERROR

spring:
  application:
    name: layui-demo #服务名
#  以下配置已经在WebConfigure这里配置了，无需再配置       
#  mvc: #表示所有的访问都经过静态资源路径，springboot的静态资源路径默认值是classpath: /static
#    static-path-pattern: /static/**  
#  resources: #覆盖默认配置，所以需要将默认的也加上否则static、public等这些路径将不能被当作静态资源路径
#    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
#编码格式
  http: 
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  jpa:
    database: oracle
    show-sql: true   #是否打印出自动生产的SQL，方便调试的时候查看
  datasource: 
#oracle配置
#      driver-class-name: oracle.jdbc.OracleDriver
#      url: jdbc:oracle:thin:@10.8.200.161:1521:ghisdev
#      username: slisoper
#      password: YU##h67YUO3
#mysql配置
#      driver-class-name: com.mysql.cj.jdbc.Driver  spring boot 2.1.0以后是这么写的
      driver-class-name: com.mysql.jdbc.Driver 
      url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF8&zeroDateTimeBehavior=convertToNull&useSSL=true&allowMultiQueries=true&serverTimezone=Asia/Hong_Kong
      username: root
      password: root
#druid连接池的设置
      druid:
        filters: stat,wall #配置扩展插件
        initial-size: 5 #初始化时建立物理连接的个数
        min-idle: 5 #最小连接池数量
        max-active: 20 #最大连接池数量 maxIdle已经不再使用
        max-wait: 60000 #获取连接时最大等待时间，单位毫秒
        test-while-idle: true #申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
        time-between-eviction-runs-millis: 60000 #既作为检测的间隔时间又作为testWhileIdel执行的依据
        min-evictable-idle-time-millis: 30000 #销毁线程时检测当前连接的最后活动时间和当前时间差大于该值时，关闭当前连接
        test-on-borrow: false #申请连接时会执行validationQuery检测连接是否有效,开启会降低性能,默认为true
        test-on-return: false #归还连接时会执行validationQuery检测连接是否有效,开启会降低性能,默认为true
        exceptionSorter: true #当数据库抛出不可恢复的异常时,抛弃该连接
        max-pool-prepared-statement-per-connection-size: 20
        connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500 #通过connectProperties属性来打开mergeSql功能；慢SQL记录
        use-global-data-source-stat: true #合并多个DruidDataSource的监控数据
#用来检测连接是否有效的sql 必须是一个查询语句
#mysql中为 select 'x'
#oracle中为 select 1 from dual
        validation-query: select 'x'

      

# 配置mybatis-plus
mybatis-plus:
  mapper-locations: classpath:org/zhulin/layui/dao/xml/*.xml # 配置扫描xml
  type-aliases-package: org.zhulin.layui.dao.entity   # 实体扫描，多个package用逗号或者分号分隔
      