spring:
  application:
    name: zipkin-hi #服务名
#服务链路追踪组件zipkin
  zipkin:
    base-url: http://localhost:9411

server:
  port: 9100  #服务提供者端口

eureka:
  client:
    serviceUrl:
      defaultZone:  http://peer1:8760/eureka/
#      defaultZone: http://localhost:8760/eureka/     


