userName: Alex
bookTitle: Spring Boot入门教程

server:
  port: 8500 #服务器端口
  tomcat:
    uri-encoding: UTF-8  

#log配置
logging:
    path: C:/E/Spring-boot/demo/user/local/log
    level: 
      com: 
        favorites: DEBUG
        baomidou.mybatisplus.samples.quickstart: debug
      org: 
        springframework.web: INFO
        hibernate: ERROR

spring:
  application:
    name: layui-demo #服务名
#  以下配置已经在WebConfigure这里配置了，无需再配置       
#  mvc: #表示所有的访问都经过静态资源路径，springboot的静态资源路径默认值是classpath: /static
#    static-path-pattern: /static/**  
#  resources: #覆盖默认配置，所以需要将默认的也加上否则static、public等这些路径将不能被当作静态资源路径
#    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
#编码格式
  http: 
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  jpa:
    database: oracle
    show-sql: true   #是否打印出自动生产的SQL，方便调试的时候查看
  datasource: 
#oracle配置
#      driver-class-name: oracle.jdbc.OracleDriver
#      url: jdbc:oracle:thin:@----:1521:ghisdev
#      username: ----
#      password: ----
#mysql配置
#      driver-class-name: com.mysql.cj.jdbc.Driver  spring boot 2.1.0以后是这么写的
#      driver-class-name: com.mysql.jdbc.Driver 
#      url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF8&zeroDateTimeBehavior=convertToNull&useSSL=true&allowMultiQueries=true&serverTimezone=Asia/Hong_Kong
#      username: root
#      password: root
#mycat数据库中间件配置
      driver-class-name: com.mysql.jdbc.Driver  #配置数据源
      url: jdbc:mysql://localhost:8066/TESTDB #mycat指定的主数据库
      username: root  #这里配置的是Mycat中server.xml中配置账号密码，不是数据库的密码。
      password: 123456
      type: com.alibaba.druid.pool.DruidDataSource #链接druid和mysql
#druid连接池的设置
      druid:
#mycat数据库中间件配置-和druid搭配----------start------------
#        driver-class-name: com.mysql.jdbc.Driver          #配置数据源
#        username: root #这里配置的是Mycat中server.xml中配置账号密码，不是数据库的密码。
#        password: 123456
#        url: jdbc:mysql://localhost:8066/TESTDB
#mycat数据库中间件配置-和druid搭配----------end------------
        filters: stat,wall #配置扩展插件
        initial-size: 5 #初始化时建立物理连接的个数
        min-idle: 5 #最小连接池数量
        max-active: 20 #最大连接池数量 maxIdle已经不再使用
        max-wait: 60000 #获取连接时最大等待时间，单位毫秒
        test-while-idle: true #申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
        time-between-eviction-runs-millis: 60000 #既作为检测的间隔时间又作为testWhileIdel执行的依据
        min-evictable-idle-time-millis: 30000 #销毁线程时检测当前连接的最后活动时间和当前时间差大于该值时，关闭当前连接
        test-on-borrow: false #申请连接时会执行validationQuery检测连接是否有效,开启会降低性能,默认为true
        test-on-return: false #归还连接时会执行validationQuery检测连接是否有效,开启会降低性能,默认为true
        exceptionSorter: true #当数据库抛出不可恢复的异常时,抛弃该连接
        max-pool-prepared-statement-per-connection-size: 20
        connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500 #通过connectProperties属性来打开mergeSql功能；慢SQL记录
        use-global-data-source-stat: true #合并多个DruidDataSource的监控数据
#用来检测连接是否有效的sql 必须是一个查询语句
#mysql中为 select 'x'
#oracle中为 select 1 from dual
#        validation-query: select 1 from dual
        validation-query: select 'x'
        
#配置RabbitMQ消息中间件    
  rabbitmq:
    host: localhost
    port: 5672
    username: root
    password: root
    publisher-confirms: true # 消息发送到交换机确认机制：开启发送确认
    publisher-returns: true   # 消息发送到交换机确认机制：开启发送失败退回
    listener:
      # 开启ACK消息确认
      direct.acknowledge-mode: manual  #采用手动应答
      simple.acknowledge-mode: manual        
#Redis配置
  redis:
    database: 0 #数据库索引（默认为0）
    host: 127.0.0.1 # Redis服务器地址
    port: 6379 # Redis服务器连接端口 
    password: 123456 # Redis服务器连接密码（默认为空）
    pool:
      max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
      max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-idle: 8 # 连接池中的最大空闲连接
      min-idle: 0 # 连接池中的最小空闲连接
    timeout: 5000 # 连接超时时间（毫秒）     

# 配置mybatis-plus
mybatis-plus:
  mapper-locations: classpath:com/layui/dao/xml/*.xml # 配置扫描xml
  type-aliases-package: com.layui.dao.entity   # 实体扫描，多个package用逗号或者分号分隔
   