spring:
  application:
    name: service-feign #服务名

server:
  port: 8765 #服务提供者端口
 
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
feign:
  hystrix:
    enabled: true  #Feign中使用Hystrix断路器