spring:
  application:
    name: config-server #服务名
  cloud:
#配置中心配置  
    config:
      label: master #配置仓库的分支
      server:
        git:
          uri: https://github.com/zhulin7914/QC/  #配置git仓库地址
          searchPaths: TC/config #配置仓库路径
          username: #访问git仓库的用户名，公共仓库可不填
          password: #访问git仓库的用户密码  ，公共仓库可不填

server:
  port: 8100  #服务提供者端口
 
eureka:
  instance:
      instance-id: config-server-1
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/      